plugin_blacklist:
# common
- actuator_control
- ftp
- safety_area
- hil
# extras
- altitude
- debug_value
- image_pub
- px4flow
- vibration
- vision_speed_estimate
- wheel_odometry
- distance_sensor #include this to prevent continuous error stream message about DS sensor mapping

plugin_whitelist: []
#- 'sys_*'
